dependencies:
  # - <organization/repo>@<version>
  - Uniswap/v3-core@1.0.0
  - OpenZeppelin/openzeppelin-contracts@3.4.1
  - Uniswap/v3-periphery@1.3.0
compiler:
  solc:
    remappings:
      - '@uniswap/v3-core=Uniswap/v3-core@1.0.0'
      - '@uniswap/v3-periphery=Uniswap/v3-periphery@1.3.0'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.1'
networks:
  development:
    verify: False
  rinkeby:
    verify: True
  ganache:
    verify: False
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}